"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { type FormEvent, type ReactNode, useState } from "react";
import { Eye, EyeOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SiteNav } from "@/components/layout/site-nav";

export function LoginForm() { const router = useRouter(); const [show, setShow] = useState(false); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); setSubmitting(true); const data = new FormData(e.currentTarget); const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: data.get("email"), password: data.get("password") }) }); const result = await response.json() as { user?: { role?: string }; error?: string }; setSubmitting(false); if (!response.ok) return setError(result.error ?? "ไม่สามารถเข้าสู่ระบบได้"); router.push(result.user?.role === "EMPLOYER" ? "/employer" : result.user?.role === "ADMIN" ? "/admin" : "/candidate"); } return <AuthCard title="เข้าสู่ระบบ" description="ยินดีต้อนรับกลับ เข้าสู่ระบบเพื่อจัดการงานและใบสมัครของคุณ"><form className="space-y-4" onSubmit={submit}><Field label="อีเมล"><Input name="email" type="email" autoComplete="email" required /></Field><Field label="รหัสผ่าน"><div className="relative"><Input name="password" type={show ? "text" : "password"} autoComplete="current-password" required /><button type="button" onClick={() => setShow(!show)} className="absolute right-1 top-1 grid size-11 place-items-center rounded-full" aria-label="แสดงหรือซ่อนรหัสผ่าน">{show ? <EyeOff className="size-5" /> : <Eye className="size-5" />}</button></div></Field>{error && <p className="text-sm text-red-700" role="alert">{error}</p>}<Button className="w-full" type="submit" disabled={submitting}>{submitting ? "กำลังเข้าสู่ระบบ..." : "เข้าสู่ระบบ"}</Button></form><p className="mt-5 text-center text-sm">ยังไม่มีบัญชี? <Link className="font-semibold text-sky-700" href="/register">สมัครสมาชิก</Link></p></AuthCard>; }
export function RegisterForm() { const router = useRouter(); const [role, setRole] = useState("candidate"); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setError(""); const data = new FormData(e.currentTarget); setSubmitting(true); const response = await fetch("/api/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ role, displayName: data.get("name"), companyName: data.get("companyName"), email: data.get("email"), password: data.get("password") }) }); const result = await response.json() as { error?: string }; setSubmitting(false); if (!response.ok) return setError(result.error ?? "ไม่สามารถสมัครสมาชิกได้"); router.push(role === "employer" ? "/employer" : "/candidate"); } return <AuthCard title="สมัครสมาชิก" description="สร้างบัญชีผู้หางานหรือผู้ประกอบการสำหรับ MVP"><form className="space-y-4" onSubmit={submit}><div className="grid grid-cols-2 gap-3"><Button type="button" variant={role === "candidate" ? "default" : "secondary"} onClick={() => setRole("candidate")}>ผู้หางาน</Button><Button type="button" variant={role === "employer" ? "default" : "secondary"} onClick={() => setRole("employer")}>ผู้ประกอบการ</Button></div>{role === "candidate" ? <Field label="ชื่อ-นามสกุล"><Input name="name" required /></Field> : <Field label="ชื่อบริษัท"><Input name="companyName" required /></Field>}<Field label="อีเมล"><Input name="email" type="email" required /></Field><Field label="รหัสผ่าน"><Input name="password" type="password" minLength={8} required /><p className="mt-1 text-xs text-slate-500">อย่างน้อย 8 ตัวอักษร</p></Field><label className="flex gap-2 text-sm"><input name="agree" type="checkbox" required />ฉันยอมรับข้อตกลงการใช้งาน</label>{error && <p className="text-sm text-red-700" role="alert">{error}</p>}<Button className="w-full" type="submit" disabled={submitting}>{submitting ? "กำลังสมัครสมาชิก..." : "สมัครสมาชิก"}</Button></form><p className="mt-5 text-center text-sm">มีบัญชีอยู่แล้ว? <Link className="font-semibold text-sky-700" href="/login">เข้าสู่ระบบ</Link></p></AuthCard>; }
function AuthCard({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <><SiteNav /><main className="mx-auto min-h-dvh max-w-3xl px-5 py-10 sm:py-14"><section className="mx-auto max-w-md border-t-4 border-sky-700 bg-white px-6 py-7 sm:px-8"><p className="text-sm font-bold uppercase tracking-[0.14em] text-sky-700">Nexspacey</p><h1 className="mt-3 text-2xl font-bold tracking-tight text-slate-950">{title}</h1><p className="mt-2 mb-7 text-sm text-slate-600">{description}</p>{children}</section></main></>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-sm font-semibold text-slate-800">{label}<span className="ml-1 text-red-700">*</span><div className="mt-1">{children}</div></label>; }
